services:
  - type: web
    name: whatsapp-video-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TWILIO_SID
        value: your_real_sid
      - key: TWILIO_AUTH_TOKEN
        value: your_real_token
